export const CATEGORIES = [
   { id: "all", label: "ទាំងអស់" },
  { id: "drinks", label: "ភេសជ្ជៈ" },
  { id: "food", label: "អាហារ" }
]
export const MENU =[
    {
    id: "1",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/11.jpg",
  },
    {
    id: "2",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/12.jpg",
  },
    {
    id: "3",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/13.jpg",
  },
    {
    id: "4",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/14.jpg",
  },
  {
    id: "5",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/15.jpg",
  },
    {
    id: "6",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/16.jpg",
  },
    {
    id: "7",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/17.jpg",
  },
    {
    id: "8",
    name: "Iced Latte",
    price: 2.50,
    category: "drink",
    image: "/images/menu/18.jpg",
  },
    {
    id: "9",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/19.jpg",
  },
    {
    id: "10",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/20.jpg",
  },
   {
    id: "11",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/1.jpg",
  },
    {
    id: "12",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/2.jpg",
  },
    {
    id: "13",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/3.jpg",
  },
    {
    id: "14",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/4.jpg",
  },
    {
    id: "15",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/10.jpg",
  },
    {
    id: "16",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/6.jpg",
  },
    {
    id: "17",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/7.jpg",
  },
    {
    id: "18",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/8.jpg",
  },
    {
    id: "19",
    name: "pizza",
    price: 3,
    category: "food",
    image: "/images/menu/9.jpg",
  },
]